package com.mercuriusxeno.goo.tools.architecture;

import org.junit.jupiter.api.Test;
import java.util.List;
import java.util.Set;
import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * The graph documents drawn from a hand-built scan: packages fold their
 * types' references into package edges, and each document prints the
 * generated-file notice, its cycles and its flowchart.
 */
class MermaidGraphDocumentTest {

    private static final String ROOT = "com.mercuriusxeno.goo.";
    private static final String RENDERER = ROOT + "client.ber.VatRenderer";
    private static final String ENTITY = ROOT + "block.VatEntity";
    private static final String HELPER = ROOT + "block.VatHelper";

    private static ScannedType type(String qualifiedName, String... references) {
        int lastDot = qualifiedName.lastIndexOf('.');
        return new ScannedType(qualifiedName.substring(0, lastDot), qualifiedName.substring(lastDot + 1),
                TypeKind.CLASS, "src/main/java/" + qualifiedName.replace('.', '/') + ".java",
                List.of(), List.of(), Set.of(references), 0);
    }

    private final List<ScannedType> scan = List.of(
            type(RENDERER, ENTITY),
            type(ENTITY, HELPER),
            type(HELPER, ENTITY));

    @Test
    void renderDrawsThePackageTopology() {
        DirectedGraph packages = DirectedGraph.ofPackages(scan);
        String document = MermaidGraphDocument.render("topology", "packages", packages,
                NodeLabels.forPackages(packages.adjacency().keySet()));
        assertEquals("""
                # topology

                Generated by ./gradlew architecture. Regenerate rather than edit.

                ## Cycles

                No cycle among these packages.


                ```mermaid
                flowchart LR
                  block
                  client_ber["client.ber"]
                  client_ber --> block
                ```
                """, document);
    }

    @Test
    void renderDrawsTheTypeDependenciesWithTheirCycle() {
        String document = MermaidGraphDocument.render("types", "types", DirectedGraph.ofTypes(scan),
                NodeLabels.forTypes(scan));
        assertEquals("""
                # types

                Generated by ./gradlew architecture. Regenerate rather than edit.

                ## Cycles

                Each line walks one set of types that all reach each other, every arrow an edge the graph holds.

                - VatEntity -> VatHelper -> VatEntity

                ```mermaid
                flowchart LR
                  VatEntity
                  VatHelper
                  VatRenderer
                  VatEntity --> VatHelper
                  VatHelper --> VatEntity
                  VatRenderer --> VatEntity
                ```
                """, document);
    }

    @Test
    void forTypesNamesThePackageBesideASharedSimpleName() {
        List<ScannedType> twins = List.of(type(ROOT + "block.Vat"), type(ROOT + "client.Vat"));
        assertEquals(List.of("Vat (block)", "Vat (client)"), List.copyOf(NodeLabels.forTypes(twins).values()));
        assertEquals("Vat__block_", MermaidGraphDocument.idOf("Vat (block)"));
    }
}
