modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
issueTrackerURL="https://github.com/MercuriusXeno/Goo/issues" #optional

[[mods]] #mandatory
    modId="goo" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Goo" #mandatory
    # updateJSONURL="" #optional
    # displayURL="" #optional
    # logoFile="" #optional
    authors="Xeno, OrionOnline" #optional
    description='''Goo is a mod about things being made of goo. You make it out of things, and you make things out of it.'''
[[dependencies.goo]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[${forge_version},)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.goo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.goo]]
    modId="aequivaleo"
    mandatory=true
    versionRange="[0.0.101-ALPHA]"
    ordering="NONE"
    side="BOTH"
[[dependencies.goo]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.2-44]"
    ordering="NONE"
    side="BOTH"
