modLoader="javafml"
loaderVersion="[${loader_version},)"
license="MIT License"
issueTrackerURL="https://github.com/MercuriusXeno/Goo/issues"

[[mods]]
    modId="goo"
    version="${goo_version}"
    displayName="Goo"
    displayURL="https://github.com/MercuriusXeno/Goo"
    authors="Xeno"
    description='''Goo is a mod about things being made of goo. You make it out of things, and you make things out of it.'''
    credits="OrionOnline (Aequivaleo), Bluberry Kat (Textures, Testing), Webmilio"
[[dependencies.goo]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goo]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.goo]]
    modId="aequivaleo"
    mandatory=true
    versionRange="[${aequivaleo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goo]]
    modId="patchouli"
    mandatory=true
    versionRange="[${patchouli_version},)"
    ordering="NONE"
    side="BOTH"