package com.xeno.goop.setup;

import net.minecraft.fluid.Fluid;
import net.minecraft.item.Item;
import net.minecraft.item.Items;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class DefaultMappings {
    public static String volatileGoop = Registry.VOLATILE_GOOP.get().getRegistryName().toString();
    public static String earthenGoop = Registry.EARTHEN_GOOP.get().getRegistryName().toString();
    public static String aquaticGoop = Registry.AQUATIC_GOOP.get().getRegistryName().toString();
    public static String esotericGoop = Registry.ESOTERIC_GOOP.get().getRegistryName().toString();
    public static String floralGoop = Registry.FLORAL_GOOP.get().getRegistryName().toString();
    public static String faunalGoop = Registry.FAUNAL_GOOP.get().getRegistryName().toString();
    public static String fungalGoop = Registry.FUNGAL_GOOP.get().getRegistryName().toString();
    public static String regalGoop = Registry.REGAL_GOOP.get().getRegistryName().toString();

    public static List<GoopValueMapping> values = new ArrayList<>();
    static {
//        addMapping(Items.ACACIA_LEAVES, goopValue(,));
//        addMapping(Items.ACACIA_LOG, goopValue(,));
//        addMapping(Items.ACACIA_SAPLING, goopValue(,));
//        addMapping(Items.ALLIUM, goopValue(,));
//        addMapping(Items.APPLE, goopValue(,));
//        addMapping(Items.AZURE_BLUET, goopValue(,));
//        addMapping(Items.BAMBOO, goopValue(,));
//        addMapping(Items.BARRIER, goopValue(,));
//        addMapping(Items.BAT_SPAWN_EGG, goopValue(,));
//        addMapping(Items.BEDROCK, goopValue(,));
//        addMapping(Items.BEE_NEST, goopValue(,));
//        addMapping(Items.BEE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.BEEF, goopValue(,));
//        addMapping(Items.BEETROOT, goopValue(,));
//        addMapping(Items.BEETROOT_SEEDS, goopValue(,));
//        addMapping(Items.BELL, goopValue(,));
//        addMapping(Items.BIRCH_LEAVES, goopValue(,));
//        addMapping(Items.BIRCH_LOG, goopValue(,));
//        addMapping(Items.BIRCH_SAPLING, goopValue(,));
//        addMapping(Items.BLACK_CONCRETE, goopValue(,));
//        addMapping(Items.BLACK_SHULKER_BOX, goopValue(,));
//        addMapping(Items.BLAZE_ROD, goopValue(,));
//        addMapping(Items.BLAZE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.BLUE_CONCRETE, goopValue(,));
//        addMapping(Items.BLUE_ORCHID, goopValue(,));
//        addMapping(Items.BLUE_SHULKER_BOX, goopValue(,));
//        addMapping(Items.BONE, goopValue(,));
//        addMapping(Items.BRAIN_CORAL, goopValue(,));
//        addMapping(Items.BRAIN_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.BRAIN_CORAL_FAN, goopValue(,));
//        addMapping(Items.BROWN_CONCRETE, goopValue(,));
//        addMapping(Items.BROWN_MUSHROOM, goopValue(,));
//        addMapping(Items.BROWN_MUSHROOM_BLOCK, goopValue(,));
//        addMapping(Items.BROWN_SHULKER_BOX, goopValue(,));
//        addMapping(Items.BUBBLE_CORAL, goopValue(,));
//        addMapping(Items.BUBBLE_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.BUBBLE_CORAL_FAN, goopValue(,));
//        addMapping(Items.CACTUS, goopValue(,));
//        addMapping(Items.CARROT, goopValue(,));
//        addMapping(Items.CARVED_PUMPKIN, goopValue(,));
//        addMapping(Items.CAT_SPAWN_EGG, goopValue(,));
//        addMapping(Items.CAVE_SPIDER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.CHAIN_COMMAND_BLOCK, goopValue(,));
//        addMapping(Items.CHAINMAIL_BOOTS, goopValue(,));
//        addMapping(Items.CHAINMAIL_CHESTPLATE, goopValue(,));
//        addMapping(Items.CHAINMAIL_HELMET, goopValue(,));
//        addMapping(Items.CHAINMAIL_LEGGINGS, goopValue(,));
        addMapping(Items.CHARCOAL, goopValue(volatileGoop, 240));
//        addMapping(Items.CHICKEN, goopValue(,));
//        addMapping(Items.CHICKEN_SPAWN_EGG, goopValue(,));
//        addMapping(Items.CHIPPED_ANVIL, goopValue(,));
//        addMapping(Items.CHORUS_FLOWER, goopValue(,));
//        addMapping(Items.CHORUS_FRUIT, goopValue(,));
//        addMapping(Items.CHORUS_PLANT, goopValue(,));
//        addMapping(Items.CLAY_BALL, goopValue(,));
//        addMapping(Items.COAL_ORE, goopValue(,));
//        addMapping(Items.COBBLESTONE, goopValue(,));
//        addMapping(Items.COBWEB, goopValue(,));
//        addMapping(Items.COCOA_BEANS, goopValue(,));
//        addMapping(Items.COD, goopValue(,));
//        addMapping(Items.COD_BUCKET, goopValue(,));
//        addMapping(Items.COD_SPAWN_EGG, goopValue(,));
//        addMapping(Items.COMMAND_BLOCK, goopValue(,));
//        addMapping(Items.COMMAND_BLOCK_MINECART, goopValue(,));
//        addMapping(Items.CORNFLOWER, goopValue(,));
//        addMapping(Items.COW_SPAWN_EGG, goopValue(,));
//        addMapping(Items.CREEPER_HEAD, goopValue(,));
//        addMapping(Items.CREEPER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.CYAN_CONCRETE, goopValue(,));
//        addMapping(Items.CYAN_SHULKER_BOX, goopValue(,));
//        addMapping(Items.DAMAGED_ANVIL, goopValue(,));
//        addMapping(Items.DANDELION, goopValue(,));
//        addMapping(Items.DARK_OAK_LEAVES, goopValue(,));
//        addMapping(Items.DARK_OAK_LOG, goopValue(,));
//        addMapping(Items.DARK_OAK_SAPLING, goopValue(,));
//        addMapping(Items.DEAD_BRAIN_CORAL, goopValue(,));
//        addMapping(Items.DEAD_BRAIN_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.DEAD_BRAIN_CORAL_FAN, goopValue(,));
//        addMapping(Items.DEAD_BUBBLE_CORAL, goopValue(,));
//        addMapping(Items.DEAD_BUBBLE_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.DEAD_BUBBLE_CORAL_FAN, goopValue(,));
//        addMapping(Items.DEAD_BUSH, goopValue(,));
//        addMapping(Items.DEAD_FIRE_CORAL, goopValue(,));
//        addMapping(Items.DEAD_FIRE_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.DEAD_FIRE_CORAL_FAN, goopValue(,));
//        addMapping(Items.DEAD_HORN_CORAL, goopValue(,));
//        addMapping(Items.DEAD_HORN_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.DEAD_HORN_CORAL_FAN, goopValue(,));
//        addMapping(Items.DEAD_TUBE_CORAL, goopValue(,));
//        addMapping(Items.DEAD_TUBE_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.DEAD_TUBE_CORAL_FAN, goopValue(,));
//        addMapping(Items.DEBUG_STICK, goopValue(,));
//        addMapping(Items.DIAMOND_HORSE_ARMOR, goopValue(,));
//        addMapping(Items.DIAMOND_ORE, goopValue(,));
//        addMapping(Items.DIRT, goopValue(,));
//        addMapping(Items.DOLPHIN_SPAWN_EGG, goopValue(,));
//        addMapping(Items.DONKEY_SPAWN_EGG, goopValue(,));
//        addMapping(Items.DRAGON_BREATH, goopValue(,));
//        addMapping(Items.DRAGON_EGG, goopValue(,));
//        addMapping(Items.DRAGON_HEAD, goopValue(,));
//        addMapping(Items.DROWNED_SPAWN_EGG, goopValue(,));
//        addMapping(Items.EGG, goopValue(,));
//        addMapping(Items.ELDER_GUARDIAN_SPAWN_EGG, goopValue(,));
//        addMapping(Items.ELYTRA, goopValue(,));
//        addMapping(Items.EMERALD_ORE, goopValue(,));
//        addMapping(Items.ENCHANTED_BOOK, goopValue(,));
//        addMapping(Items.ENCHANTED_GOLDEN_APPLE, goopValue(,));
//        addMapping(Items.END_PORTAL_FRAME, goopValue(,));
//        addMapping(Items.END_STONE, goopValue(,));
//        addMapping(Items.ENDER_PEARL, goopValue(,));
//        addMapping(Items.ENDERMAN_SPAWN_EGG, goopValue(,));
//        addMapping(Items.ENDERMITE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.EVOKER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.EXPERIENCE_BOTTLE, goopValue(,));
//        addMapping(Items.FARMLAND, goopValue(,));
//        addMapping(Items.FEATHER, goopValue(,));
//        addMapping(Items.FERN, goopValue(,));
//        addMapping(Items.FILLED_MAP, goopValue(,));
//        addMapping(Items.FIRE_CORAL, goopValue(,));
//        addMapping(Items.FIRE_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.FIRE_CORAL_FAN, goopValue(,));
//        addMapping(Items.FLINT, goopValue(,));
//        addMapping(Items.FOX_SPAWN_EGG, goopValue(,));
//        addMapping(Items.GHAST_SPAWN_EGG, goopValue(,));
//        addMapping(Items.GHAST_TEAR, goopValue(,));
//        addMapping(Items.GLOBE_BANNER_PATTERN, goopValue(,));
//        addMapping(Items.GLOWSTONE_DUST, goopValue(,));
//        addMapping(Items.GOLD_ORE, goopValue(,));
//        addMapping(Items.GOLDEN_HORSE_ARMOR, goopValue(,));
//        addMapping(Items.GRASS, goopValue(,));
//        addMapping(Items.GRASS_BLOCK, goopValue(,));
//        addMapping(Items.GRASS_PATH, goopValue(,));
//        addMapping(Items.GRAVEL, goopValue(,));
//        addMapping(Items.GRAY_CONCRETE, goopValue(,));
//        addMapping(Items.GRAY_SHULKER_BOX, goopValue(,));
//        addMapping(Items.GREEN_CONCRETE, goopValue(,));
//        addMapping(Items.GREEN_SHULKER_BOX, goopValue(,));
//        addMapping(Items.GUARDIAN_SPAWN_EGG, goopValue(,));
//        addMapping(Items.GUNPOWDER, goopValue(,));
//        addMapping(Items.HEART_OF_THE_SEA, goopValue(,));
//        addMapping(Items.HONEYCOMB, goopValue(,));
//        addMapping(Items.HORN_CORAL, goopValue(,));
//        addMapping(Items.HORN_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.HORN_CORAL_FAN, goopValue(,));
//        addMapping(Items.HORSE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.HUSK_SPAWN_EGG, goopValue(,));
//        addMapping(Items.ICE, goopValue(,));
//        addMapping(Items.INFESTED_CHISELED_STONE_BRICKS, goopValue(,));
//        addMapping(Items.INFESTED_COBBLESTONE, goopValue(,));
//        addMapping(Items.INFESTED_CRACKED_STONE_BRICKS, goopValue(,));
//        addMapping(Items.INFESTED_MOSSY_STONE_BRICKS, goopValue(,));
//        addMapping(Items.INFESTED_STONE, goopValue(,));
//        addMapping(Items.INFESTED_STONE_BRICKS, goopValue(,));
//        addMapping(Items.INK_SAC, goopValue(,));
//        addMapping(Items.IRON_HORSE_ARMOR, goopValue(,));
//        addMapping(Items.IRON_ORE, goopValue(,));
//        addMapping(Items.JIGSAW, goopValue(,));
//        addMapping(Items.JUNGLE_LEAVES, goopValue(,));
//        addMapping(Items.JUNGLE_LOG, goopValue(,));
//        addMapping(Items.JUNGLE_SAPLING, goopValue(,));
//        addMapping(Items.KELP, goopValue(,));
//        addMapping(Items.KNOWLEDGE_BOOK, goopValue(,));
//        addMapping(Items.LAPIS_ORE, goopValue(,));
//        addMapping(Items.LARGE_FERN, goopValue(,));
//        addMapping(Items.LAVA_BUCKET, goopValue(,));
//        addMapping(Items.LIGHT_BLUE_CONCRETE, goopValue(,));
//        addMapping(Items.LIGHT_BLUE_SHULKER_BOX, goopValue(,));
//        addMapping(Items.LIGHT_GRAY_CONCRETE, goopValue(,));
//        addMapping(Items.LIGHT_GRAY_SHULKER_BOX, goopValue(,));
//        addMapping(Items.LILAC, goopValue(,));
//        addMapping(Items.LILY_OF_THE_VALLEY, goopValue(,));
//        addMapping(Items.LILY_PAD, goopValue(,));
//        addMapping(Items.LIME_CONCRETE, goopValue(,));
//        addMapping(Items.LIME_SHULKER_BOX, goopValue(,));
//        addMapping(Items.LINGERING_POTION, goopValue(,));
//        addMapping(Items.LLAMA_SPAWN_EGG, goopValue(,));
//        addMapping(Items.MAGENTA_CONCRETE, goopValue(,));
//        addMapping(Items.MAGENTA_SHULKER_BOX, goopValue(,));
//        addMapping(Items.MAGMA_CUBE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.MELON_SLICE, goopValue(,));
//        addMapping(Items.MILK_BUCKET, goopValue(,));
//        addMapping(Items.MOOSHROOM_SPAWN_EGG, goopValue(,));
//        addMapping(Items.MULE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.MUSHROOM_STEM, goopValue(,));
//        addMapping(Items.MUSIC_DISC_11, goopValue(,));
//        addMapping(Items.MUSIC_DISC_13, goopValue(,));
//        addMapping(Items.MUSIC_DISC_BLOCKS, goopValue(,));
//        addMapping(Items.MUSIC_DISC_CAT, goopValue(,));
//        addMapping(Items.MUSIC_DISC_CHIRP, goopValue(,));
//        addMapping(Items.MUSIC_DISC_FAR, goopValue(,));
//        addMapping(Items.MUSIC_DISC_MALL, goopValue(,));
//        addMapping(Items.MUSIC_DISC_MELLOHI, goopValue(,));
//        addMapping(Items.MUSIC_DISC_STAL, goopValue(,));
//        addMapping(Items.MUSIC_DISC_STRAD, goopValue(,));
//        addMapping(Items.MUSIC_DISC_WAIT, goopValue(,));
//        addMapping(Items.MUSIC_DISC_WARD, goopValue(,));
//        addMapping(Items.MUTTON, goopValue(,));
//        addMapping(Items.MYCELIUM, goopValue(,));
//        addMapping(Items.NAME_TAG, goopValue(,));
//        addMapping(Items.NAUTILUS_SHELL, goopValue(,));
//        addMapping(Items.NETHER_QUARTZ_ORE, goopValue(,));
//        addMapping(Items.NETHER_STAR, goopValue(,));
//        addMapping(Items.NETHER_WART, goopValue(,));
//        addMapping(Items.NETHERRACK, goopValue(,));
//        addMapping(Items.OAK_LEAVES, goopValue(,));
//        addMapping(Items.OAK_LOG, goopValue(,));
//        addMapping(Items.OAK_SAPLING, goopValue(,));
//        addMapping(Items.OBSIDIAN, goopValue(,));
//        addMapping(Items.OCELOT_SPAWN_EGG, goopValue(,));
//        addMapping(Items.ORANGE_CONCRETE, goopValue(,));
//        addMapping(Items.ORANGE_SHULKER_BOX, goopValue(,));
//        addMapping(Items.ORANGE_TULIP, goopValue(,));
//        addMapping(Items.OXEYE_DAISY, goopValue(,));
//        addMapping(Items.PANDA_SPAWN_EGG, goopValue(,));
//        addMapping(Items.PARROT_SPAWN_EGG, goopValue(,));
//        addMapping(Items.PEONY, goopValue(,));
//        addMapping(Items.PETRIFIED_OAK_SLAB, goopValue(,));
//        addMapping(Items.PHANTOM_MEMBRANE, goopValue(,));
//        addMapping(Items.PHANTOM_SPAWN_EGG, goopValue(,));
//        addMapping(Items.PIG_SPAWN_EGG, goopValue(,));
//        addMapping(Items.PILLAGER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.PINK_CONCRETE, goopValue(,));
//        addMapping(Items.PINK_SHULKER_BOX, goopValue(,));
//        addMapping(Items.PINK_TULIP, goopValue(,));
//        addMapping(Items.PLAYER_HEAD, goopValue(,));
//        addMapping(Items.PODZOL, goopValue(,));
//        addMapping(Items.POISONOUS_POTATO, goopValue(,));
//        addMapping(Items.POLAR_BEAR_SPAWN_EGG, goopValue(,));
//        addMapping(Items.POPPY, goopValue(,));
//        addMapping(Items.PORKCHOP, goopValue(,));
//        addMapping(Items.POTATO, goopValue(,));
//        addMapping(Items.POTION, goopValue(,));
//        addMapping(Items.PRISMARINE_CRYSTALS, goopValue(,));
//        addMapping(Items.PRISMARINE_SHARD, goopValue(,));
//        addMapping(Items.PUFFERFISH, goopValue(,));
//        addMapping(Items.PUFFERFISH_BUCKET, goopValue(,));
//        addMapping(Items.PUFFERFISH_SPAWN_EGG, goopValue(,));
//        addMapping(Items.PUMPKIN, goopValue(,));
//        addMapping(Items.PURPLE_CONCRETE, goopValue(,));
//        addMapping(Items.PURPLE_SHULKER_BOX, goopValue(,));
//        addMapping(Items.RABBIT, goopValue(,));
//        addMapping(Items.RABBIT_FOOT, goopValue(,));
//        addMapping(Items.RABBIT_HIDE, goopValue(,));
//        addMapping(Items.RABBIT_SPAWN_EGG, goopValue(,));
//        addMapping(Items.RAVAGER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.RED_CONCRETE, goopValue(,));
//        addMapping(Items.RED_MUSHROOM, goopValue(,));
//        addMapping(Items.RED_MUSHROOM_BLOCK, goopValue(,));
//        addMapping(Items.RED_SAND, goopValue(,));
//        addMapping(Items.RED_SHULKER_BOX, goopValue(,));
//        addMapping(Items.RED_TULIP, goopValue(,));
//        addMapping(Items.REDSTONE_ORE, goopValue(,));
//        addMapping(Items.REPEATING_COMMAND_BLOCK, goopValue(,));
//        addMapping(Items.ROSE_BUSH, goopValue(,));
//        addMapping(Items.ROTTEN_FLESH, goopValue(,));
//        addMapping(Items.SADDLE, goopValue(,));
//        addMapping(Items.SALMON, goopValue(,));
//        addMapping(Items.SALMON_BUCKET, goopValue(,));
//        addMapping(Items.SALMON_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SAND, goopValue(,));
//        addMapping(Items.SCUTE, goopValue(,));
//        addMapping(Items.SEA_PICKLE, goopValue(,));
//        addMapping(Items.SEAGRASS, goopValue(,));
//        addMapping(Items.SHEEP_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SHULKER_SHELL, goopValue(,));
//        addMapping(Items.SHULKER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SILVERFISH_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SKELETON_HORSE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SKELETON_SKULL, goopValue(,));
//        addMapping(Items.SKELETON_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SLIME_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SNOWBALL, goopValue(,));
//        addMapping(Items.SOUL_SAND, goopValue(,));
//        addMapping(Items.SPAWNER, goopValue(,));
//        addMapping(Items.SPIDER_EYE, goopValue(,));
//        addMapping(Items.SPIDER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.SPLASH_POTION, goopValue(,));
//        addMapping(Items.SPRUCE_LEAVES, goopValue(,));
//        addMapping(Items.SPRUCE_LOG, goopValue(,));
//        addMapping(Items.SPRUCE_SAPLING, goopValue(,));
//        addMapping(Items.SQUID_SPAWN_EGG, goopValue(,));
//        addMapping(Items.STRAY_SPAWN_EGG, goopValue(,));
//        addMapping(Items.STRING, goopValue(,));
//        addMapping(Items.STRIPPED_ACACIA_LOG, goopValue(,));
//        addMapping(Items.STRIPPED_BIRCH_LOG, goopValue(,));
//        addMapping(Items.STRIPPED_DARK_OAK_LOG, goopValue(,));
//        addMapping(Items.STRIPPED_JUNGLE_LOG, goopValue(,));
//        addMapping(Items.STRIPPED_OAK_LOG, goopValue(,));
//        addMapping(Items.STRIPPED_SPRUCE_LOG, goopValue(,));
//        addMapping(Items.STRUCTURE_BLOCK, goopValue(,));
//        addMapping(Items.STRUCTURE_VOID, goopValue(,));
//        addMapping(Items.SUGAR_CANE, goopValue(,));
//        addMapping(Items.SUNFLOWER, goopValue(,));
//        addMapping(Items.SUSPICIOUS_STEW, goopValue(,));
//        addMapping(Items.SWEET_BERRIES, goopValue(,));
//        addMapping(Items.TALL_GRASS, goopValue(,));
//        addMapping(Items.TIPPED_ARROW, goopValue(,));
//        addMapping(Items.TOTEM_OF_UNDYING, goopValue(,));
//        addMapping(Items.TRADER_LLAMA_SPAWN_EGG, goopValue(,));
//        addMapping(Items.TRIDENT, goopValue(,));
//        addMapping(Items.TROPICAL_FISH, goopValue(,));
//        addMapping(Items.TROPICAL_FISH_BUCKET, goopValue(,));
//        addMapping(Items.TROPICAL_FISH_SPAWN_EGG, goopValue(,));
//        addMapping(Items.TUBE_CORAL, goopValue(,));
//        addMapping(Items.TUBE_CORAL_BLOCK, goopValue(,));
//        addMapping(Items.TUBE_CORAL_FAN, goopValue(,));
//        addMapping(Items.TURTLE_EGG, goopValue(,));
//        addMapping(Items.TURTLE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.VEX_SPAWN_EGG, goopValue(,));
//        addMapping(Items.VILLAGER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.VINDICATOR_SPAWN_EGG, goopValue(,));
//        addMapping(Items.VINE, goopValue(,));
//        addMapping(Items.WANDERING_TRADER_SPAWN_EGG, goopValue(,));
//        addMapping(Items.WATER_BUCKET, goopValue(,));
//        addMapping(Items.WET_SPONGE, goopValue(,));
//        addMapping(Items.WHEAT_SEEDS, goopValue(,));
//        addMapping(Items.WHITE_CONCRETE, goopValue(,));
//        addMapping(Items.WHITE_SHULKER_BOX, goopValue(,));
//        addMapping(Items.WHITE_TULIP, goopValue(,));
//        addMapping(Items.WITCH_SPAWN_EGG, goopValue(,));
//        addMapping(Items.WITHER_ROSE, goopValue(,));
//        addMapping(Items.WITHER_SKELETON_SKULL, goopValue(,));
//        addMapping(Items.WITHER_SKELETON_SPAWN_EGG, goopValue(,));
//        addMapping(Items.WOLF_SPAWN_EGG, goopValue(,));
//        addMapping(Items.WRITTEN_BOOK, goopValue(,));
//        addMapping(Items.YELLOW_CONCRETE, goopValue(,));
//        addMapping(Items.YELLOW_SHULKER_BOX, goopValue(,));
//        addMapping(Items.ZOMBIE_HEAD, goopValue(,));
//        addMapping(Items.ZOMBIE_HORSE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.ZOMBIE_PIGMAN_SPAWN_EGG, goopValue(,));
//        addMapping(Items.ZOMBIE_SPAWN_EGG, goopValue(,));
//        addMapping(Items.ZOMBIE_VILLAGER_SPAWN_EGG, goopValue(,));

    }

    private static GoopValue goopValue(String s, int i) {
        return new GoopValue(s, i);
    }

    private static void addMapping(Item item, GoopValue... args) {
        addMapping(item.getRegistryName().toString(), args);
    }

    private static void addMapping(String resourceLocation, GoopValue... args) {
        values.add(new GoopValueMapping(resourceLocation, new ArrayList<>(Arrays.asList(args))));
    }

}
