package com.mercuriusxeno.goo.tools.architecture;

import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Writes a directed graph as a markdown document: a title, the generated-file
 * notice, a Cycles section, then the graph as a mermaid flowchart whose node
 * ids are the labels with every character mermaid rejects replaced.
 */
public final class MermaidGraphDocument {

    /** The line every generated architecture document opens with under its title. */
    public static final String GENERATED_NOTICE = "Generated by ./gradlew architecture. Regenerate rather than edit.";
    private static final String TITLE_LINE = "# %s\n\n%s\n\n";
    private static final String CYCLES_HEADING = "## Cycles\n\n";
    private static final String NO_CYCLE_LINE = "No cycle among these %s.\n\n";
    private static final String CYCLES_INTRO = "Each line walks one set of %s that all reach each other, every arrow an edge the graph holds.\n\n";
    private static final String CYCLE_LINE = "- %s\n";
    private static final String CYCLE_STEP = " -> ";
    private static final String FLOWCHART_OPEN = "\n```mermaid\nflowchart LR\n";
    private static final String FLOWCHART_CLOSE = "```\n";
    private static final String NODE_LINE = "  %s\n";
    private static final String LABELLED_NODE_LINE = "  %s[\"%s\"]\n";
    private static final String EDGE_LINE = "  %s --> %s\n";
    private static final String ID_FILLER = "_";
    private static final Pattern MERMAID_ID_REJECTS = Pattern.compile("[^A-Za-z0-9_]");

    /**
     * Holds only static members.
     */
    private MermaidGraphDocument() {
    }

    /**
     * Renders the document.
     *
     * @param title     the document's title
     * @param nodeNoun  the plural noun the Cycles section names the nodes by, such as {@code packages}
     * @param graph     the graph
     * @param labels    each node mapped to the label it prints as
     * @return the markdown text
     */
    public static String render(String title, String nodeNoun, DirectedGraph graph, Map<String, String> labels) {
        StringBuilder text = new StringBuilder();
        text.append(String.format(TITLE_LINE, title, GENERATED_NOTICE));
        text.append(cyclesSection(nodeNoun, CycleFinder.find(graph), labels));
        text.append(FLOWCHART_OPEN);
        graph.adjacency().keySet().forEach(node -> text.append(nodeLine(labels.get(node))));
        graph.adjacency().forEach((source, targets) -> targets.forEach(target -> text.append(
                String.format(EDGE_LINE, idOf(labels.get(source)), idOf(labels.get(target))))));
        text.append(FLOWCHART_CLOSE);
        return text.toString();
    }

    /**
     * Renders the Cycles section.
     *
     * @param nodeNoun the plural noun for the nodes
     * @param cycles   each cycle's walk
     * @param labels   each node mapped to its label
     * @return the section's markdown
     */
    public static String cyclesSection(String nodeNoun, List<List<String>> cycles, Map<String, String> labels) {
        return CYCLES_HEADING + cycleList(nodeNoun, cycles, labels);
    }

    /**
     * Renders the cycles as a list under a sentence saying what each line is,
     * or the one line saying there is none.
     *
     * @param nodeNoun the plural noun for the nodes
     * @param cycles   each cycle's walk
     * @param labels   each node mapped to its label
     * @return the markdown, without a heading
     */
    public static String cycleList(String nodeNoun, List<List<String>> cycles, Map<String, String> labels) {
        StringBuilder text = new StringBuilder();
        if (cycles.isEmpty()) {
            return text.append(String.format(NO_CYCLE_LINE, nodeNoun)).toString();
        }
        text.append(String.format(CYCLES_INTRO, nodeNoun));
        for (List<String> cycle : cycles) {
            List<String> walk = cycle.stream().map(labels::get).toList();
            text.append(String.format(CYCLE_LINE, String.join(CYCLE_STEP, walk)));
        }
        return text.toString();
    }

    /**
     * The declaration line of one node: its bare id when the id reads as the label, else the id and the label.
     *
     * @param label the node's label
     * @return the flowchart line
     */
    private static String nodeLine(String label) {
        String id = idOf(label);
        return id.equals(label) ? String.format(NODE_LINE, id) : String.format(LABELLED_NODE_LINE, id, label);
    }

    /**
     * The mermaid id a label prints under.
     *
     * @param label the node's label
     * @return the label with every character outside letters, digits and underscore replaced by an underscore
     */
    static String idOf(String label) {
        return MERMAID_ID_REJECTS.matcher(label).replaceAll(ID_FILLER);
    }
}
